### ISSUE TITLE
Multiple QR codes shown when using the widget

### ISSUE THREAD

**Issue by ghost** [getyoti/wordpress#4]
Hey, I was playing around with the Yoti plugin and I noticed that if I clicked log in with Yoti when using the widget I got multiple QR codes. See screenshot.

Also, I noticed that I can not add Yoti as the login for the admin, is that by design?

![screenshot from 2017-07-16 23-51-24](https://user-images.githubusercontent.com/22009476/28251993-d56d8bb6-6a81-11e7-831a-35b6fb95ee97.png)

**Comment by zarembas** [comment]
Hi @leonard-kramer The multiple QR codes bug will be fixed in the next version of the Yoti button. It's not something related to the WordPress plugin. The admin login doesn't use Yoti because it's quite hard to link a Yoti user to a certain account.
